import numpy as np
#theta1, theta2, theta3, theta4, theta5, theta6, theta7 = 0,0,0,0,0,0,0
theta1, theta2, theta3, theta4, theta5, theta6, theta7 = np.pi,np.pi/2,np.pi/3,np.pi/4,np.pi/5,np.pi/6,np.pi/7
J = np.array([[0, -np.cos(theta1), -np.sin(theta1)*np.sin(theta2), np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3), 
               (-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.sin(theta4) - np.sin(theta1)*np.sin(theta2)*np.cos(theta4), 
               -((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) + np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.sin(theta5) + (np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.cos(theta5), 
               (((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) + np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.cos(theta5) + (np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.sin(theta5))*np.sin(theta6) + ((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.sin(theta4) - np.sin(theta1)*np.sin(theta2)*np.cos(theta4))*np.cos(theta6)],
     
            [-1, 0, -np.cos(theta2), -np.sin(theta2)*np.sin(theta3), np.sin(theta2)*np.sin(theta4)*np.cos(theta3) - np.cos(theta2)*np.cos(theta4), 
             -(np.sin(theta2)*np.cos(theta3)*np.cos(theta4) + np.sin(theta4)*np.cos(theta2))*np.sin(theta5) - np.sin(theta2)*np.sin(theta3)*np.cos(theta5), 
             ((np.sin(theta2)*np.cos(theta3)*np.cos(theta4) + np.sin(theta4)*np.cos(theta2))*np.cos(theta5) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5))*np.sin(theta6) + (np.sin(theta2)*np.sin(theta4)*np.cos(theta3) - np.cos(theta2)*np.cos(theta4))*np.cos(theta6)],
            
            [0, -np.sin(theta1), np.sin(theta2)*np.cos(theta1), -np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2), (-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) + np.sin(theta2)*np.cos(theta1)*np.cos(theta4), 
             -((-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) - np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.sin(theta5) + (-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.cos(theta5), 
             (((-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) - np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.cos(theta5) + (-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.sin(theta5))*np.sin(theta6) + ((-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) + np.sin(theta2)*np.cos(theta1)*np.cos(theta4))*np.cos(theta6)],
     
            [(-0.2251*((np.sin(theta1)*np.sin(theta3) - np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) + np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.cos(theta5) - 0.2251*(np.sin(theta1)*np.cos(theta3) + np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.sin(theta5))*np.sin(theta6) + (-0.2251*(np.sin(theta1)*np.sin(theta3) - np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) + 0.2251*np.sin(theta2)*np.cos(theta1)*np.cos(theta4))*np.cos(theta6) + (-0.32*np.sin(theta1)*np.sin(theta3) + 0.32*np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) + 0.32*np.sin(theta2)*np.cos(theta1)*np.cos(theta4) + 0.3*np.sin(theta2)*np.cos(theta1), 
             (-0.2251*(np.sin(theta1)*np.sin(theta2)*np.cos(theta3)*np.cos(theta4) + np.sin(theta1)*np.sin(theta4)*np.cos(theta2))*np.cos(theta5) + 0.2251*np.sin(theta1)*np.sin(theta2)*np.sin(theta3)*np.sin(theta5))*np.sin(theta6) + (-0.2251*np.sin(theta1)*np.sin(theta2)*np.sin(theta4)*np.cos(theta3) + 0.2251*np.sin(theta1)*np.cos(theta2)*np.cos(theta4))*np.cos(theta6) - 0.32*np.sin(theta1)*np.sin(theta2)*np.sin(theta4)*np.cos(theta3) + 0.32*np.sin(theta1)*np.cos(theta2)*np.cos(theta4) + 0.3*np.sin(theta1)*np.cos(theta2), 
             (-0.2251*(np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.cos(theta4)*np.cos(theta5) - 0.2251*(np.sin(theta1)*np.cos(theta2)*np.cos(theta3) + np.sin(theta3)*np.cos(theta1))*np.sin(theta5))*np.sin(theta6) + (-0.32*np.sin(theta1)*np.sin(theta3)*np.cos(theta2) + 0.32*np.cos(theta1)*np.cos(theta3))*np.sin(theta4) - 0.2251*(np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.sin(theta4)*np.cos(theta6), 
             -0.2251*(-(-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.sin(theta4) + np.sin(theta1)*np.sin(theta2)*np.cos(theta4))*np.sin(theta6)*np.cos(theta5) + (-0.2251*(-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) - 0.2251*np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.cos(theta6) + (0.32*np.sin(theta1)*np.cos(theta2)*np.cos(theta3) + 0.32*np.sin(theta3)*np.cos(theta1))*np.cos(theta4) - 0.32*np.sin(theta1)*np.sin(theta2)*np.sin(theta4), 
             (0.2251*((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) + np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.sin(theta5) - 0.2251*(np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.cos(theta5))*np.sin(theta6), 
             (-0.2251*((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) + np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.cos(theta5) - 0.2251*(np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.sin(theta5))*np.cos(theta6) - (-0.2251*(-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.sin(theta4) + 0.2251*np.sin(theta1)*np.sin(theta2)*np.cos(theta4))*np.sin(theta6), 0], 
            
            [0, (-0.2251*(-np.sin(theta2)*np.sin(theta4) + np.cos(theta2)*np.cos(theta3)*np.cos(theta4))*np.cos(theta5) + 0.2251*np.sin(theta3)*np.sin(theta5)*np.cos(theta2))*np.sin(theta6) + (-0.2251*np.sin(theta2)*np.cos(theta4) - 0.2251*np.sin(theta4)*np.cos(theta2)*np.cos(theta3))*np.cos(theta6) - 0.32*np.sin(theta2)*np.cos(theta4) - 0.3*np.sin(theta2) - 0.32*np.sin(theta4)*np.cos(theta2)*np.cos(theta3), (0.2251*np.sin(theta2)*np.sin(theta3)*np.cos(theta4)*np.cos(theta5) + 0.2251*np.sin(theta2)*np.sin(theta5)*np.cos(theta3))*np.sin(theta6) + 0.2251*np.sin(theta2)*np.sin(theta3)*np.sin(theta4)*np.cos(theta6) + 0.32*np.sin(theta2)*np.sin(theta3)*np.sin(theta4), 
             -0.2251*(-np.sin(theta2)*np.sin(theta4)*np.cos(theta3) + np.cos(theta2)*np.cos(theta4))*np.sin(theta6)*np.cos(theta5) + (-0.2251*np.sin(theta2)*np.cos(theta3)*np.cos(theta4) - 0.2251*np.sin(theta4)*np.cos(theta2))*np.cos(theta6) - 0.32*np.sin(theta2)*np.cos(theta3)*np.cos(theta4) - 0.32*np.sin(theta4)*np.cos(theta2), 
             (0.2251*(np.sin(theta2)*np.cos(theta3)*np.cos(theta4) + np.sin(theta4)*np.cos(theta2))*np.sin(theta5) + 0.2251*np.sin(theta2)*np.sin(theta3)*np.cos(theta5))*np.sin(theta6), (-0.2251*(np.sin(theta2)*np.cos(theta3)*np.cos(theta4) + np.sin(theta4)*np.cos(theta2))*np.cos(theta5) + 0.2251*np.sin(theta2)*np.sin(theta3)*np.sin(theta5))*np.cos(theta6) - (-0.2251*np.sin(theta2)*np.sin(theta4)*np.cos(theta3) + 0.2251*np.cos(theta2)*np.cos(theta4))*np.sin(theta6), 0],
     
            [(-0.2251*((-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.cos(theta4) + np.sin(theta1)*np.sin(theta2)*np.sin(theta4))*np.cos(theta5) - 0.2251*(np.sin(theta1)*np.sin(theta3)*np.cos(theta2) - np.cos(theta1)*np.cos(theta3))*np.sin(theta5))*np.sin(theta6) + (-0.2251*(-np.sin(theta1)*np.cos(theta2)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1))*np.sin(theta4) + 0.2251*np.sin(theta1)*np.sin(theta2)*np.cos(theta4))*np.cos(theta6) + (0.32*np.sin(theta1)*np.cos(theta2)*np.cos(theta3) + 0.32*np.sin(theta3)*np.cos(theta1))*np.sin(theta4) + 0.32*np.sin(theta1)*np.sin(theta2)*np.cos(theta4) + 0.3*np.sin(theta1)*np.sin(theta2), 
             (-0.2251*(-np.sin(theta2)*np.cos(theta1)*np.cos(theta3)*np.cos(theta4) - np.sin(theta4)*np.cos(theta1)*np.cos(theta2))*np.cos(theta5) - 0.2251*np.sin(theta2)*np.sin(theta3)*np.sin(theta5)*np.cos(theta1))*np.sin(theta6) + (0.2251*np.sin(theta2)*np.sin(theta4)*np.cos(theta1)*np.cos(theta3) - 0.2251*np.cos(theta1)*np.cos(theta2)*np.cos(theta4))*np.cos(theta6) + 0.32*np.sin(theta2)*np.sin(theta4)*np.cos(theta1)*np.cos(theta3) - 0.32*np.cos(theta1)*np.cos(theta2)*np.cos(theta4) - 0.3*np.cos(theta1)*np.cos(theta2), 
             (-0.2251*(np.sin(theta1)*np.sin(theta3) - np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta5) - 0.2251*(-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.cos(theta4)*np.cos(theta5))*np.sin(theta6) - 0.2251*(-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.sin(theta4)*np.cos(theta6) + (0.32*np.sin(theta1)*np.cos(theta3) + 0.32*np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.sin(theta4), 
             -0.2251*(-(-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) - np.sin(theta2)*np.cos(theta1)*np.cos(theta4))*np.sin(theta6)*np.cos(theta5) + (-0.2251*(-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) + 0.2251*np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.cos(theta6) + (0.32*np.sin(theta1)*np.sin(theta3) - 0.32*np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) + 0.32*np.sin(theta2)*np.sin(theta4)*np.cos(theta1), 
             (0.2251*((-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) - np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.sin(theta5) - 0.2251*(-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.cos(theta5))*np.sin(theta6), 
             (-0.2251*((-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.cos(theta4) - np.sin(theta2)*np.sin(theta4)*np.cos(theta1))*np.cos(theta5) - 0.2251*(-np.sin(theta1)*np.cos(theta3) - np.sin(theta3)*np.cos(theta1)*np.cos(theta2))*np.sin(theta5))*np.cos(theta6) - (-0.2251*(-np.sin(theta1)*np.sin(theta3) + np.cos(theta1)*np.cos(theta2)*np.cos(theta3))*np.sin(theta4) - 0.2251*np.sin(theta2)*np.cos(theta1)*np.cos(theta4))*np.sin(theta6), 0]])

print(J)