import numpy as np
#theta1, theta2, theta3, theta4, theta5, theta6, theta7 = 0,0,0,0,0,0,0
theta1, theta2, theta3, theta4, theta5, theta6, theta7 = np.np.pi,np.np.pi/2,np.np.pi/3,np.np.pi/4,np.np.pi/5,np.np.pi/6,np.np.pi/7
J = np.array([
    [0,
     -np.sin(theta1 + np.pi/2), np.cos(theta1 + np.pi/2)*np.sin(theta2), 
     np.cos(theta1 + np.pi/2)*np.sin(theta2), 
     - np.cos(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3),
     np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2) - np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)),
     np.sin(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) - np.cos(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)),
     np.cos(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) - np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + np.sin(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)))],
     [
         -1,
         0,
         -np.cos(theta2),
         -np.sin(theta2)*np.sin(theta3),
         np.cos(theta3)*np.sin(theta2)*np.sin(theta4) - np.cos(theta2)*np.cos(theta4),
         - np.sin(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) - np.cos(theta5)*np.sin(theta2)*np.sin(theta3),
         np.sin(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5)) - np.cos(theta6)*(np.cos(theta2)*np.cos(theta4) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4))
     ],
     [
         0,
         np.cos(theta1 + np.pi/2),
         np.sin(theta2)*np.sin(theta1 + np.pi/2),
         np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2),
         np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2),
         np.cos(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)),
         np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) + np.sin(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) + np.cos(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2))
     ],
     [
         l4*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2)) + l5*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) + np.sin(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) + np.cos(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2))) + l6*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) + np.sin(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) + np.cos(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2))) + l3*np.sin(theta2)*np.sin(theta1 + np.pi/2),
         l5*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) - np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta3)*np.sin(theta5)) - np.cos(theta6)*(np.cos(theta2)*np.cos(theta4)*np.cos(theta1 + np.pi/2) - np.cos(theta3)*np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4))) - l4*(np.cos(theta2)*np.cos(theta4)*np.cos(theta1 + np.pi/2) - np.cos(theta3)*np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + l6*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) - np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta3)*np.sin(theta5)) - np.cos(theta6)*(np.cos(theta2)*np.cos(theta4)*np.cos(theta1 + np.pi/2) - np.cos(theta3)*np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4))) - l3*np.cos(theta2)*np.cos(theta1 + np.pi/2), l4*np.sin(theta4)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)) - l6*(np.sin(theta6)*(np.sin(theta5)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))) - np.cos(theta6)*np.sin(theta4)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))) - l5*(np.sin(theta6)*(np.sin(theta5)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))) - np.cos(theta6)*np.sin(theta4)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))),
         l5*(np.cos(theta6)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) - np.cos(theta5)*np.sin(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2))) + l6*(np.cos(theta6)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) - np.cos(theta5)*np.sin(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2))) + l4*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)),
         l5*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) - np.cos(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))) - l6*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) - np.cos(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3))),
         l5*(np.sin(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) - np.cos(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + np.sin(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)))) - l6*(np.sin(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) - np.cos(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + np.sin(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)))),
         0
     ],
     [
         0,
         l5*(np.sin(theta6)*(np.cos(theta5)*(np.sin(theta2)*np.sin(theta4) - np.cos(theta2)*np.cos(theta3)*np.cos(theta4)) + np.cos(theta2)*np.sin(theta3)*np.sin(theta5)) - np.cos(theta6)*(np.cos(theta4)*np.sin(theta2) + np.cos(theta2)*np.cos(theta3)*np.sin(theta4))) + l6*(np.sin(theta6)*(np.cos(theta5)*(np.sin(theta2)*np.sin(theta4) - np.cos(theta2)*np.cos(theta3)*np.cos(theta4)) + np.cos(theta2)*np.sin(theta3)*np.sin(theta5)) - np.cos(theta6)*(np.cos(theta4)*np.sin(theta2) + np.cos(theta2)*np.cos(theta3)*np.sin(theta4))) - l4*(np.cos(theta4)*np.sin(theta2) + np.cos(theta2)*np.cos(theta3)*np.sin(theta4)) - l3*np.sin(theta2),
         l5*(np.sin(theta6)*(np.cos(theta3)*np.sin(theta2)*np.sin(theta5) + np.cos(theta4)*np.cos(theta5)*np.sin(theta2)*np.sin(theta3)) + np.cos(theta6)*np.sin(theta2)*np.sin(theta3)*np.sin(theta4)) + l6*(np.sin(theta6)*(np.cos(theta3)*np.sin(theta2)*np.sin(theta5) + np.cos(theta4)*np.cos(theta5)*np.sin(theta2)*np.sin(theta3)) + np.cos(theta6)*np.sin(theta2)*np.sin(theta3)*np.sin(theta4)) + l4*np.sin(theta2)*np.sin(theta3)*np.sin(theta4),
         - l4*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) - l5*(np.cos(theta6)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) + np.cos(theta5)*np.sin(theta6)*(np.cos(theta2)*np.cos(theta4) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4))) - l6*(np.cos(theta6)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) + np.cos(theta5)*np.sin(theta6)*(np.cos(theta2)*np.cos(theta4) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4))),
         l5*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) + np.cos(theta5)*np.sin(theta2)*np.sin(theta3)) + l6*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) + np.cos(theta5)*np.sin(theta2)*np.sin(theta3)),
         - l5*(np.cos(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5)) + np.sin(theta6)*(np.cos(theta2)*np.cos(theta4) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4))) - l6*(np.cos(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.sin(theta4) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5)) + np.sin(theta6)*(np.cos(theta2)*np.cos(theta4) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4))),
         0
     ],
     [
         l4*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) + l5*(np.cos(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) + np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + np.sin(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)))) + l6*(np.cos(theta6)*(np.sin(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta1 + np.pi/2)*np.sin(theta2)) + np.sin(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.sin(theta3)*np.sin(theta1 + np.pi/2) - np.cos(theta2)*np.cos(theta3)*np.cos(theta1 + np.pi/2)) + np.cos(theta1 + np.pi/2)*np.sin(theta2)*np.sin(theta4)) + np.sin(theta5)*(np.cos(theta3)*np.sin(theta1 + np.pi/2) + np.cos(theta2)*np.cos(theta1 + np.pi/2)*np.sin(theta3)))) - l3*np.cos(theta1 + np.pi/2)*np.sin(theta2),
         l5*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5)*np.sin(theta1 + np.pi/2)) - np.cos(theta6)*(np.cos(theta2)*np.cos(theta4)*np.sin(theta1 + np.pi/2) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2))) + l6*(np.sin(theta6)*(np.cos(theta5)*(np.cos(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2) + np.cos(theta3)*np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta3)*np.sin(theta5)*np.sin(theta1 + np.pi/2)) - np.cos(theta6)*(np.cos(theta2)*np.cos(theta4)*np.sin(theta1 + np.pi/2) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2))) - l4*(np.cos(theta2)*np.cos(theta4)*np.sin(theta1 + np.pi/2) - np.cos(theta3)*np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - l3*np.cos(theta2)*np.sin(theta1 + np.pi/2),
         l5*(np.sin(theta6)*(np.sin(theta5)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) - np.cos(theta6)*np.sin(theta4)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) + l6*(np.sin(theta6)*(np.sin(theta5)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.cos(theta4)*np.cos(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) - np.cos(theta6)*np.sin(theta4)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) - l4*np.sin(theta4)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2)),
         - l4*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - l5*(np.cos(theta6)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - np.cos(theta5)*np.sin(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2))) - l6*(np.cos(theta6)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - np.cos(theta5)*np.sin(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2))),
         l5*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - np.cos(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))) + l6*np.sin(theta6)*(np.sin(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) - np.cos(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2))),
         l5*(np.sin(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2)) - np.cos(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) + np.sin(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2)))) + l6*(np.sin(theta6)*(np.sin(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) + np.cos(theta4)*np.sin(theta2)*np.sin(theta1 + np.pi/2)) - np.cos(theta6)*(np.cos(theta5)*(np.cos(theta4)*(np.cos(theta1 + np.pi/2)*np.sin(theta3) + np.cos(theta2)*np.cos(theta3)*np.sin(theta1 + np.pi/2)) - np.sin(theta2)*np.sin(theta4)*np.sin(theta1 + np.pi/2)) + np.sin(theta5)*(np.cos(theta3)*np.cos(theta1 + np.pi/2) - np.cos(theta2)*np.sin(theta3)*np.sin(theta1 + np.pi/2)))),
         0
     ]

    ])
print(J)